// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBERtum-7ahSTRGK8TGENQsCgraPu1cIbc',
    appId: '1:607926820029:web:ee71437c77fa50c062abd4',
    messagingSenderId: '607926820029',
    projectId: 'aiesec-minha-jornada',
    authDomain: 'aiesec-minha-jornada.firebaseapp.com',
    storageBucket: 'aiesec-minha-jornada.firebasestorage.app',
    measurementId: 'G-7P1BM2PE1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf2WJ7TTmRl-I_Xu8p4R1bEL1dDC3QrPM',
    appId: '1:607926820029:android:717bb05bd60e37df62abd4',
    messagingSenderId: '607926820029',
    projectId: 'aiesec-minha-jornada',
    storageBucket: 'aiesec-minha-jornada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAURL3NyU9fpmFoM63FoQQMq2W7vdstn04',
    appId: '1:607926820029:ios:afd6a1be463c6c2b62abd4',
    messagingSenderId: '607926820029',
    projectId: 'aiesec-minha-jornada',
    storageBucket: 'aiesec-minha-jornada.firebasestorage.app',
    iosClientId: '607926820029-lssuraia0vmch8pupv0nd9g28dlsjb9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiesecMinhaJornada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAURL3NyU9fpmFoM63FoQQMq2W7vdstn04',
    appId: '1:607926820029:ios:afd6a1be463c6c2b62abd4',
    messagingSenderId: '607926820029',
    projectId: 'aiesec-minha-jornada',
    storageBucket: 'aiesec-minha-jornada.firebasestorage.app',
    iosClientId: '607926820029-lssuraia0vmch8pupv0nd9g28dlsjb9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiesecMinhaJornada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBERtum-7ahSTRGK8TGENQsCgraPu1cIbc',
    appId: '1:607926820029:web:e4d6034adc674afa62abd4',
    messagingSenderId: '607926820029',
    projectId: 'aiesec-minha-jornada',
    authDomain: 'aiesec-minha-jornada.firebaseapp.com',
    storageBucket: 'aiesec-minha-jornada.firebasestorage.app',
    measurementId: 'G-0V2P2SCMW8',
  );
}
